tls:
  options:
    default:
      minVersion: VersionTLS12
      sniStrict: true
      cipherSuites:
        - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
        - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
        - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
      curvePreferences:
        - CurveP384

http:
  middlewares:
    security-headers:
      headers:
        stsSeconds: 31536000
        stsPreload: true
        stsIncludeSubdomains: false
        frameDeny: true
        contentTypeNosniff: true
        referrerPolicy: no-referrer
        permissionsPolicy: none

    api-headers:
      headers:
        contentSecurityPolicy: default-src 'none'
