# based on https://community.sonarsource.com/t/how-to-use-sonarcloud-with-a-forked-repository-on-github/7363/30
# for some reason this is heinously complicated

name: Sonarcloud

on:
  workflow_run:
    workflows: [Build]
    types: [completed]

jobs:
  sonarcloud:
    name: Sonarcloud
    runs-on: ubuntu-latest

    # sonarcloud only runs on the main repo, not forks
    if: github.repository == 'se310-t6/politicry'

    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.workflow_run.head_repository.full_name }}
          ref: ${{ github.event.workflow_run.head_branch }}
          fetch-depth: 0

      - name: 📶 Download code coverage
        uses: actions/github-script@v5
        with:
          script: |
            const allArtifacts = await github.rest.actions.listWorkflowRunArtifacts({
              owner: context.repo.owner,
              repo: context.repo.repo,
              run_id: context.payload.workflow_run.id,
            });

            const names = ["cov-extension", "cov-website", "cov-backend"];
            for (const artifact of allArtifacts.data.artifacts) {
              if (names.includes(artifact.name)) {
                const download = await github.rest.actions.downloadArtifact({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  artifact_id: artifact.id,
                  archive_format: 'zip',
                });
                const fs = require('fs');
                fs.writeFileSync(`${process.env.GITHUB_WORKSPACE}/${artifact.name}.zip`, Buffer.from(download.data));
              }
            }

      - name: 📂 Unzip code coverage
        run: |
          unzip cov-extension.zip -d ./extension/coverage
          unzip cov-website.zip -d ./website/coverage
          unzip cov-backend.zip -d ./backend/coverage
          ls ./extension/coverage
          ls ./backend/coverage

      - name: 📶 Download PR number
        if: github.event.workflow_run.event == 'pull_request'
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.name }}
          run_id: ${{ github.event.workflow_run.id }}
          name: PR_NUMBER

      - name: 📶 Read PR number
        if: github.event.workflow_run.event == 'pull_request'
        id: pr_number
        uses: juliangruber/read-file-action@v1
        with:
          path: ./PR_NUMBER.txt

      - name: 📶 Download PR info
        if: github.event.workflow_run.event == 'pull_request'
        uses: octokit/request-action@v2.x
        id: get_pr_data
        with:
          route: GET /repos/{full_name}/pulls/{number}
          number: ${{ steps.pr_number.outputs.content }}
          full_name: ${{ github.event.repository.full_name }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 🔊 SonarCloud Scan (for PRs)
        if: github.event.workflow_run.event == 'pull_request'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }}
            -Dsonar.pullrequest.key=${{ fromJson(steps.get_pr_data.outputs.data).number }}
            -Dsonar.pullrequest.branch=${{ fromJson(steps.get_pr_data.outputs.data).head.ref }}
            -Dsonar.pullrequest.base=${{ fromJson(steps.get_pr_data.outputs.data).base.ref }}
            -Dsonar.coverage.exclusions=**/cypress/**/*.*
            -Dsonar.javascript.lcov.reportPaths=./extension/coverage/lcov.info,./website/coverage/lcov.info
            -Dsonar.python.coverage.reportPaths=./backend/coverage/coverage.xml
            -Dsonar.python.version=3.10
            -Dsonar.projectKey=se310-t6_politicry
            -Dsonar.organization=se310-t6

      - name: 🔊 SonarCloud Scan (for branches)
        if: github.event.workflow_run.event != 'pull_request'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.scm.revision=${{ github.event.workflow_run.head_sha }}
            -Dsonar.pullrequest.branch.name=${{ github.event.workflow_run.head_branch }}
            -Dsonar.coverage.exclusions=**/cypress/**/*.*
            -Dsonar.javascript.lcov.reportPaths=./extension/coverage/lcov.info,./website/coverage/lcov.info
            -Dsonar.python.coverage.reportPaths=./backend/coverage/coverage.xml
            -Dsonar.python.version=3.10
            -Dsonar.projectKey=se310-t6_politicry
            -Dsonar.organization=se310-t6
