name: Test

on: [push, pull_request]

jobs:
  test-and-coverage-backend:
    runs-on: ubuntu-latest
    name: Test and Coverage Backend

    steps:
      - name: Check out source repository
        uses: actions/checkout@v2

      - name: Setup environment
        run: |
          sudo apt-get update
          sudo apt-get upgrade -y
          sudo add-apt-repository -y ppa:deadsnakes/ppa
          sudo apt-get update
          sudo apt install -y python3.10 python3-pip --fix-missing

      - name: Install Python Requirements
        run: |
          pip install -r backend/requirements.txt
          pip install -r backend/dev-requirements.txt

      - name: Initialize Database
        run: |
          cd backend
          flask db stamp head
          flask db migrate
          flask db upgrade
        env:
          FLASK_APP: app.py

      - name: Run Tests
        run: |
          cd extension
          yarn
          yarn test:ci

      - name: Run Frontend Tests
        run: |
          cd website
          yarn
          yarn test

      - name: Run Backend Tests
        run: |
          cd backend
          python -m pytest -v

      - name: Generate Backend Coverage Report
        run: |
          cd backend
          coverage run --branch --context=ci --source src -m pytest
          coverage report
          coverage xml

      - name: Upload Coverage Report
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./backend/coverage.xml,./extension/coverage/clover.xml,./website/coverage/clover.xml
          fail_ci_if_error: true
          verbose: true
